#!/bin/sh -e

# .postinst has no network and root password is set.

useradd \
    --uid "$INTUNE_UID" \
    --gid "$INTUNE_GID" \
    --groups sudo \
    --create-home \
    --home-dir "$INTUNE_HOME" \
    --password "$( awk -F: '/^root:/ {print $2}' /etc/shadow )" \
    --shell /bin/bash \
    "$INTUNE_USER"

if [ -f /root/.ssh/authorized_keys ]
then
    mkdir "$INTUNE_HOME/.ssh"
    cp /root/.ssh/authorized_keys "$INTUNE_HOME/.ssh/"
fi

chown -R "$INTUNE_UID:$INTUNE_GID" "$INTUNE_HOME"
