---
name: build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get --yes update
          sudo apt-get --yes install bubblewrap pandoc
          sudo pip3 install git+https://github.com/systemd/mkosi.git
      - name: Build image
        run: |
          make
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            mkosi.output
